Repository utkarsh1235/hacktoberfest2k19, pull requests merged in 2019-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: good first issue

#2 Update README.md
  README.md
Labels: good first issue

#3 Update README.md
  README.md
Labels: good first issue

#4 Update README.md
  README.md
Labels: good first issue

#5 updated README.md
  README.md
Labels: good first issue, hacktoberfest, ready for review

#6 updated README.md
  README.md
Labels: good first issue, hacktoberfest, ready for review

#7 updated README.md
  README.md
Labels: good first issue, hacktoberfest, ready for review

#8 Updated README.md
  README.md
Labels: good first issue, hacktoberfest, ready for review

#9 Update README.md
  README.md
Labels: good first issue, hacktoberfest, ready for review

#11 Update README.md
  README.md
Labels: good first issue, hacktoberfest, ready for review

#12 Update README.md
  README.md
Labels: good first issue, hacktoberfest, ready for review

#13 Update README.md
  README.md
Labels: good first issue, hacktoberfest, ready for review

#14 Update README.md
  README.md
Labels: good first issue, hacktoberfest, ready for review

#20 Aritra pull req 17
  README.md
Labels: good first issue, hacktoberfest, ready for review

#21 Aritra Pull req 69
  README.md
Labels: good first issue, hacktoberfest, ready for review

#25 Update README.md
  README.md
Labels: good first issue, hacktoberfest, ready for review

#29 haswanth90
  README.md
Labels: good first issue, hacktoberfest, ready for review

#32 haswanth91
  README.md
Labels: good first issue, hacktoberfest, ready for review

#36 Update README.md
  README.md
Labels: good first issue, hacktoberfest, ready for review

#40 haswanth93
  README.md
Labels: good first issue, hacktoberfest, ready for review

#43 haswanth567
  README.md
Labels: good first issue, hacktoberfest, ready for review

#44 haswanth765
  README.md
Labels: good first issue, hacktoberfest, ready for review

#46 swapnil 999
  README.md
Labels: good first issue, hacktoberfest, ready for review

#47 swapnil 1000
  README.md
Labels: good first issue, hacktoberfest, ready for review

#51 new pull request 3
  README.md
Labels: good first issue, hacktoberfest, ready for review

#57 Add pull request 27
  README.md
Labels: good first issue, hacktoberfest, ready for review

#73 Dijkstra Algorithm code
  Dijkstra_algo.cpp
Labels: enhancement, hacktoberfest, ready for review

#75 Update README.md
  README.md
Labels: good first issue, hacktoberfest, ready for review

#78 Create reverse a number
  reverse a number
Labels: good first issue, hacktoberfest, ready for review

#88 harshit36
  README.md
Labels: good first issue, hacktoberfest, ready for review
